//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        public int GoodsId { get; set; }
        public int CategoryId { get; set; }
        public int AccountId { get; set; }
        public string Title { get; set; }
        public string Price { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Category Category { get; set; }
    }
}
